services:
  - type: web
    name: vieurl-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.backend.wsgi:application --bind 0.0.0.0:$PORT --chdir backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: backend
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
