services:
  - type: web
    name: vieurl-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn video_downloader.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: video_downloader.settings
